# Generated by Django 5.2.7 on 2026-03-31 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('completed_at__isnull', True)), fields=('user', 'quiz'), name='unique_active_attempt_per_user_quiz'),
        ),
    ]
