# Generated by Django 5.2.7 on 2026-06-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='answer_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
