# Generated by Django 5.2.7 on 2026-07-23 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_answer_order_index_and_more'),
        ('simulation', '0002_simulationresult_answer_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationresult',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_results', to='content.quiz'),
        ),
    ]
