# Generated by Django 5.2.7 on 2026-04-28 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=5)),
                ('strong_domains', models.JSONField(default=list)),
                ('weak_domains', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwinSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('content_id', models.IntegerField()),
                ('simulated_score', models.IntegerField(blank=True, null=True)),
                ('simulated_time_seconds', models.IntegerField(blank=True, null=True)),
                ('difficulty_perception', models.IntegerField(blank=True, choices=[(1, 'Too Easy'), (2, 'Easy'), (3, 'Appropriate'), (4, 'Hard'), (5, 'Too Hard')], null=True)),
                ('llm_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='twins.twin')),
            ],
        ),
    ]
