# Generated by Django 5.2.7 on 2026-04-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twin',
            name='reading_speed',
            field=models.IntegerField(default=1.2),
        ),
    ]
