# Generated by Django 5.2.7 on 2026-06-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twins', '0002_digitaltwin_behavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='learning_style',
            field=models.CharField(choices=[('visual', 'Visuel'), ('practical', 'Pratique'), ('theoretical', 'Théorique'), ('exercise_based', 'Basé sur exercices'), ('mixed', 'Mixte')], default='mixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='preferred_content_type',
            field=models.CharField(choices=[('text', 'Texte'), ('video', 'Vidéo'), ('quiz', 'Quiz'), ('image', 'Image'), ('interactive', 'Interactif'), ('mixed', 'Mixte')], default='mixed', max_length=20),
        ),
    ]
