# Generated by Django 5.2.7 on 2026-04-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_educationalprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationalprofile',
            old_name='level',
            new_name='education_level',
        ),
        migrations.RenameField(
            model_name='educationalprofile',
            old_name='school_name',
            new_name='school',
        ),
        migrations.RemoveField(
            model_name='educationalprofile',
            name='class_name',
        ),
        migrations.AddField(
            model_name='educationalprofile',
            name='diploma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationalprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationalprofile',
            name='institution_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
