# Generated by Django 5.2.7 on 2026-07-23 13:52

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_level_educationalprofile_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'admin')], default=2),
        ),
    ]
