# Generated by Django 5.2.7 on 2026-06-20 21:37

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_course_created_by_quiz_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='content_Course_content_type_ContentType',
        ),
        migrations.RemoveConstraint(
            model_name='quiz',
            name='content_Quiz_content_type_ContentType',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='course',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_published',
        ),
        migrations.AddField(
            model_name='answer',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='source_type',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(1, 'manual'), (2, 'import_file')], default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='content.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='source_type',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(1, 'manual'), (2, 'import_file')], default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', [1, 2])), name='content_Course_source_type_ContentSourceType'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', [1, 2])), name='content_Quiz_source_type_ContentSourceType'),
        ),
    ]
