# Generated by Django 5.2.7 on 2026-06-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_course_user_alter_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='content_Course_source_type_ContentSourceType',
        ),
        migrations.RemoveConstraint(
            model_name='quiz',
            name='content_Quiz_source_type_ContentSourceType',
        ),
        migrations.AlterField(
            model_name='course',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('import_file', 'Import File')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('import_file', 'Import File')], default='manual', max_length=20),
        ),
    ]
