# Generated by Django 5.2.7 on 2026-06-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_course_content_course_source_type_contentsourcetype_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='content_Question_question_type_QuestionType',
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('true_false', 'True / False')], default='single_choice', max_length=30),
        ),
    ]
