# Generated by Django 5.2.7 on 2026-06-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_question_content_question_question_type_questiontype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='order_index',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order_index',
        ),
    ]
